### ISSUE TITLE
XGC GENE IO issue on Summit

### ISSUE THREAD

**Issue by Damilare06** [SCOREC/wdmapp_coupling#80]
**Spack install**
on Summit, I was able to spack install `wdmapp@0.1.0%gcc@8.1.1` and `effis`.
Using this and `spectrum-mpi-10.3.1.2`, I turned on/ off the appropriate flags in the `spconfig.py` to match those shown here https://wdmapp.readthedocs.io/en/latest/machines/aimos.html - which should build the correct versions of both codes once I point them to the correct code base CMakeLists.

**Code versions used**
gene: https://github.com/phyboyzhang/gene.git @ `external_cpl` branch
xgc_devel: https://github.com/wdmapp/XGC-Devel.git @ `rpi` branch
coupler: https://github.com/phyboyzhang/wdmapp_coupling-1.git @ `szDev` branch

**Running jobs**
Using the job script provided here https://github.com/wdmapp/testcases/tree/master/run_1/summit, I was able to run all three codes, however, both gene and xgc_devel fail upon reading their first input file and/or directory. 

gene
```2: 0:  MPI_THREAD_SINGLE initialized.
2: 0:  
2: 0: *****************************************************
2: 0: ***** This is GENE 11 (release 1.9 - alpha 0) *******
2: 0: *****************************************************
2: 0:  
2: 0:  ./out err:           30  
2: 0: PROBLEM WITH FILE IO, PLEASE CHECK IF DIAGDIR EXISTS!
~                                                             
```

xgc_devel
```3: 0: --------------------------------------------------------------
3: 0: MPI_COMM_WORLD communicator : 7 nodes, 256 MPI tasks
3: 0: COMMUNICATOR NODE # [NODE NAME] : (# OF MPI TASKS) TASK # LIST
3: 0: MPI_COMM_WORLD NODE 0 [ f31n11 ] : ( 22 MPI TASKS ) 0-21
3: 0: MPI_COMM_WORLD NODE 1 [ f31n17 ] : ( 42 MPI TASKS ) 223: 0: -63 
3: 0: MPI_COMM_WORLD NODE 2 [ f33n14 ] : ( 42 MPI TASKS ) 64-105
3: 0: MPI_COMM_WORLD NODE 3 [ h22n16 ] : ( 42 MPI TASKS ) 106-147
3: 0: MPI_COMM_WORLD NODE 4 [ h26n10 ] : ( 42 MPI TASKS ) 148-189
3: 0: MPI_COMM_WORLD NODE 5 [ h26n11 ] : ( 42 MPI TASKS ) 190-231
3: 0: MPI_COMM_WORLD NODE 6 [ h26n12 ] : ( 24 MPI TASKS ) 232-255
3: 0: --------------------------------------------------------------
3: 0: At line 77 of file /ccs/home/damilare/dev/XGC-Devel/XGC_core/my_mpi.F90 (unit = 14) 
3: 0: Fortran runtime error: Cannot open file 'TASKMAP_Color0.txt': Read-only file system
3: 0:  
3: 0: Error termination. Backtrace:
3: 166:  (t_initf) Read in prof_inparam namelist from: input
3: 150:  (t_initf) Read in prof_inparam namelist from: input
```

The coupler runs correctly. 
I have tried building different branches of gene and xgc_devel but they both return the same error.

**Comment by cwsmith** [comment]
The Summit (and Rhea, etc.) compute nodes can only read and write files on the `[Member|Project|WORLD] WORK` portions of the filesystem.  
https://docs.olcf.ornl.gov/data/storage_overview.html#storage-areas
Are the jobs being run from one of these locations?

**Comment by Damilare06** [comment]
I am not sure but this is the location I run the job from /autofs/nccs-svm1_home1/damilare/dev/testcases/run_1/summit_abj

**Comment by cwsmith** [comment]
The user guide has the info:

https://docs.olcf.ornl.gov/data/user_centric.html
https://docs.olcf.ornl.gov/data/project_centric.html#

**Comment by Damilare06** [comment]
Thanks Cameron, it has gone past this error. All 3 executables run but I have to fix an HDF5 flag in gene.

**Comment by Damilare06** [comment]
HDF5 is having issues opening the XGC mesh file

```3: 0: **********************************************  
3: 0: *** Importing XGC grid XGC_map_circular_2020_new.h5***  
3: 0: **********************************************  
3: 1: HDF5-DIAG: Error detected in HDF5 (1.10.4) MPI-process 1:
3: 1:   #000: H5F.c line 509 in H5Fopen(): unable to open file
3: 1:     major: File accessibilty
3: 1:     minor: Unable to open file
3: 1:   #001: H5Fint.c line 1400 in H5F__open(): unable to open file
3: 1:     major: File accessibilty
3: 1:     minor: Unable to open file
3: 5: HDF5-DIAG: Error detected in HDF5 (1.10.4) MPI-process 5:
3: 5:   #000: H5F.c line 509 in H5Fopen(): unable to open file
3: 5:     major: File accessibilty
3: 5:     minor: Unable to open file
3: 5:   #001: H5Fint.c line 1400 in H5F__open(): unable to open file
3: 5:     major: File accessibilty
3: 5:     minor: Unable to open file
3: 5:   #002: H5Fint.c line 1546 in H5F_open(): unable to open file: time = Tue Jul 14 15:36:06 2020
3: 5: , name = './XGC_map_circular_2020_new.h5', tent_flags = 1 
3: 5:     major: File accessibilty
3: 5:     minor: Unable to open file
3: 5:   #003: H5FD.c line 734 in H5FD_open(): open failed
3: 5:     major: Virtual File Layer
3: 5:     minor: Unable to initialize object
3: 5:   #004: H5FDsec2.c line 346 in H5FD_sec2_open(): unable to open file: name = './XGC_map_circular_2020_new.h5', errno = 30, error message = 'Read-only file system', flags = 1, o_flags = 2 
3: 5:     major: File accessibilty
3: 5:     minor: Unable to open file
```

**Comment by cwsmith** [comment]
Try submitting the job with EFFIS following the run instructions here:
https://wdmapp.readthedocs.io/en/latest/machines/summit.html#running-the-cyclone-test-case

**Comment by Damilare06** [comment]
the `effis-compose.py run_1.yaml` command returns the below error: is this an error with my effis install or my run_1.yaml file?


```[damilare@login3.summit run_1]$ spack load wdmapp /sjti2y7                                                                                                                                                         
[damilare@login3.summit run_1]$  spack load effis /bbawtrv                                                                                                                                                         
[damilare@login3.summit run_1]$ effis-compose.py run_1.yaml 
Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/effis-develop-bbawtrvxljo4nh2jhb5tpy537sne5cg3/bin/effis-compose.py", line 1092, in <module>
    kittiejob = KittieJob(args.configfile)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/effis-develop-bbawtrvxljo4nh2jhb5tpy537sne5cg3/bin/effis-compose.py", line 1063, in __init__
    self.init(yamlfile)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/effis-develop-bbawtrvxljo4nh2jhb5tpy537sne5cg3/bin/effis-compose.py", line 456, in init
    self._MakeReplacements()
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/effis-develop-bbawtrvxljo4nh2jhb5tpy537sne5cg3/bin/effis-compose.py", line 276, in _MakeReplacements
    match = self._MakeReplacements(include=include)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/effis-develop-bbawtrvxljo4nh2jhb5tpy537sne5cg3/bin/effis-compose.py", line 276, in _MakeReplacements
    match = self._MakeReplacements(include=include)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/effis-develop-bbawtrvxljo4nh2jhb5tpy537sne5cg3/bin/effis-compose.py", line 276, in _MakeReplacements
    match = self._MakeReplacements(include=include)
  [Previous line repeated 966 more times]
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/effis-develop-bbawtrvxljo4nh2jhb5tpy537sne5cg3/bin/effis-compose.py", line 208, in _MakeReplacements
    searchstr = yaml.dump(self.config, default_flow_style=False, Dumper=self.OrderedDumper)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/py-pyyaml-5.1.2-enyoh7chok25ritpadc2d7d2i5cutmsc/lib/python3.7/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/py-pyyaml-5.1.2-enyoh7chok25ritpadc2d7d2i5cutmsc/lib/python3.7/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/autofs/nccs-svm1_home1/damilare/dev/spack/opt/spack/linux-rhel7-power9le/gcc-8.1.1/py-pyyaml-5.1.2-enyoh7chok25ritpadc2d7d2i5cutmsc/lib/python3.7/site-packages/yaml/representer.py", line 27, in represen
t
    node = self...
```

**Comment by cwsmith** [comment]
@Damilare06 Hmmm.  It looks like it is failing during a text replacement operation (`_MakeReplacements`) I just pushed an effis composition file that *should* work on summit (I have not tested it).  Would you please try it (add `git@github.com:SCOREC/testcases.git` as a remote and checkout the `externalCplParam`) ?

**Comment by Damilare06** [comment]
I would do that now. Thank you

**Comment by Damilare06** [comment]
must all executables be in scratch?

**Comment by Damilare06** [comment]
Thanks cameron, the new file worked... all 3 executables are running, just some debugging needed

**Comment by Damilare06** [comment]
@cwsmith it doesnt allow me to reuse the same directory each time...

**Comment by Damilare06** [comment]
and must it separate std err from std::out?
